# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea1777fe690d68d61af66c161d5fe62f208adea3696ea7ced50941651b4d6a5420f445c68bd8886fb7d8f9840b432e585d9c3c2f08d47370664c0bb4078b0b51

test:
  secret_key_base: 6d54fbebda8654148589a570ccbc3a2390f69b6059e8b74e12ddced85cc4f41ed50a5d11ad415699cf77e384bb67ed6419fa31a0696687b6143981784b014c44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
